# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-13 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0004_sorttree_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorttree',
            name='domain',
        ),
    ]
