# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0005_remove_sorttree_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorttree',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=None),
        ),
    ]
