# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-10-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0006_sorttree_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='actions',
            field=models.TextField(blank=True, default='', verbose_name='note of where the actions made in this clip'),
        ),
    ]
